services:
    kernel.listener.skillbertorequestlistener:
        class: Skillberto\RoutingExtraBundle\EventListener\SkillbertoRequestListener
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }
        arguments:
            doctrine: "@doctrine.orm.entity_manager"
    skillberto.routingextra.admin.page:
        class: Skillberto\RoutingExtraBundle\Admin\PageAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: skillberto_page, label: Page }
        arguments: [null, Skillberto\RoutingExtraBundle\Entity\Page, SkillbertoRoutingExtraBundle:PageAdmin]        